version: '3.8'

services:
  user:
    build: ./microservices
    command: uvicorn user_service.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./microservices:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0


